import type { Metric, Badge, ChallengeTemplate } from '@/types';

export const METRICS_75_HARD: Metric[] = [
  {
    id: 'steps',
    name: '10K Steps',
    type: 'number',
    target: 10000,
    comparison: 'gte',
    unit: 'steps',
    required: true,
  },
  {
    id: 'screen_time',
    name: 'Screen Time < 3h',
    type: 'number',
    target: 180,
    comparison: 'lte',
    unit: 'min',
    required: true,
  },
  {
    id: 'pickups',
    name: 'Pickups < 100',
    type: 'number',
    target: 100,
    comparison: 'lte',
    unit: '',
    required: true,
  },
  {
    id: 'water',
    name: '½ Gallon Water',
    type: 'boolean',
    required: true,
  },
  {
    id: 'alcohol',
    name: 'No Alcohol',
    type: 'boolean',
    required: true,
  },
  {
    id: 'weed',
    name: 'Weed Usage',
    type: 'count',
    tracking: true,
    required: false,
  },
  {
    id: 'masturbation',
    name: 'Masturbation',
    type: 'count',
    tracking: true,
    required: false,
  },
  {
    id: 'workout',
    name: '45min Workout',
    type: 'boolean',
    required: false,
  },
  {
    id: 'photo',
    name: 'Daily Photo',
    type: 'photo',
    required: true,
  },
];

export const METRICS_75_SOFT: Metric[] = [
  {
    id: 'steps',
    name: '8K Steps',
    type: 'number',
    target: 8000,
    comparison: 'gte',
    unit: 'steps',
    required: true,
  },
  {
    id: 'screen_time',
    name: 'Screen Time < 4h',
    type: 'number',
    target: 240,
    comparison: 'lte',
    unit: 'min',
    required: true,
  },
  {
    id: 'water',
    name: '½ Gallon Water',
    type: 'boolean',
    required: true,
  },
  {
    id: 'workout',
    name: '30min Exercise',
    type: 'boolean',
    required: true,
  },
  {
    id: 'reading',
    name: '10min Reading',
    type: 'boolean',
    required: true,
  },
];

export const METRICS_30_DAY: Metric[] = [
  {
    id: 'main_goal',
    name: 'Daily Goal',
    type: 'boolean',
    required: true,
  },
  {
    id: 'reflection',
    name: 'Daily Reflection',
    type: 'boolean',
    required: false,
  },
];

// Comprehensive library of preset metrics organized by category
export type PresetCategory = {
  id: string;
  name: string;
  icon: string;
  metrics: Metric[];
};

export const PRESET_METRICS: PresetCategory[] = [
  {
    id: 'fitness',
    name: 'Fitness & Exercise',
    icon: '💪',
    metrics: [
      {
        id: 'steps_10k',
        name: '10K Steps',
        type: 'number',
        target: 10000,
        comparison: 'gte',
        unit: 'steps',
        required: true,
        icon: 'steps',
      },
      {
        id: 'steps_8k',
        name: '8K Steps',
        type: 'number',
        target: 8000,
        comparison: 'gte',
        unit: 'steps',
        required: true,
        icon: 'steps',
      },
      {
        id: 'steps_5k',
        name: '5K Steps',
        type: 'number',
        target: 5000,
        comparison: 'gte',
        unit: 'steps',
        required: true,
        icon: 'steps',
      },
      {
        id: 'workout_45',
        name: '45min Workout',
        type: 'boolean',
        required: true,
        icon: 'workout',
      },
      {
        id: 'workout_30',
        name: '30min Workout',
        type: 'boolean',
        required: true,
        icon: 'workout',
      },
      {
        id: 'workout_60',
        name: '1 Hour Workout',
        type: 'boolean',
        required: true,
        icon: 'workout',
      },
      {
        id: 'gym',
        name: 'Go to Gym',
        type: 'boolean',
        required: true,
        icon: 'workout',
      },
      {
        id: 'yoga',
        name: 'Yoga Session',
        type: 'boolean',
        required: false,
        icon: 'meditation',
      },
      {
        id: 'stretching',
        name: '10min Stretching',
        type: 'boolean',
        required: false,
        icon: 'workout',
      },
      {
        id: 'running',
        name: 'Go for a Run',
        type: 'boolean',
        required: true,
        icon: 'steps',
      },
      {
        id: 'active_calories',
        name: 'Active Calories',
        type: 'number',
        target: 500,
        comparison: 'gte',
        unit: 'cal',
        required: true,
        icon: 'energy',
      },
    ],
  },
  {
    id: 'hydration',
    name: 'Hydration & Diet',
    icon: '💧',
    metrics: [
      {
        id: 'water_half_gallon',
        name: '½ Gallon Water',
        type: 'boolean',
        required: true,
        icon: 'water',
      },
      {
        id: 'water_gallon',
        name: '1 Gallon Water',
        type: 'boolean',
        required: true,
        icon: 'water',
      },
      {
        id: 'water_liters',
        name: 'Drink 2L Water',
        type: 'number',
        target: 2,
        comparison: 'gte',
        unit: 'L',
        required: true,
        icon: 'water',
      },
      {
        id: 'no_alcohol',
        name: 'No Alcohol',
        type: 'boolean',
        required: true,
        icon: 'alcohol',
      },
      {
        id: 'healthy_eating',
        name: 'Healthy Eating',
        type: 'boolean',
        required: true,
        icon: 'diet',
      },
      {
        id: 'no_sugar',
        name: 'No Added Sugar',
        type: 'boolean',
        required: true,
        icon: 'diet',
      },
      {
        id: 'no_junk_food',
        name: 'No Junk Food',
        type: 'boolean',
        required: true,
        icon: 'diet',
      },
      {
        id: 'calorie_limit',
        name: 'Stay Under Calories',
        type: 'number',
        target: 2000,
        comparison: 'lte',
        unit: 'cal',
        required: true,
        icon: 'diet',
      },
      {
        id: 'protein_intake',
        name: 'Protein Intake',
        type: 'number',
        target: 100,
        comparison: 'gte',
        unit: 'g',
        required: true,
        icon: 'diet',
      },
      {
        id: 'intermittent_fasting',
        name: 'Intermittent Fasting',
        type: 'boolean',
        required: true,
        icon: 'clock',
      },
      {
        id: 'no_eating_after_8',
        name: 'No Eating After 8PM',
        type: 'boolean',
        required: true,
        icon: 'clock',
      },
    ],
  },
  {
    id: 'digital',
    name: 'Screen Time & Digital',
    icon: '📱',
    metrics: [
      {
        id: 'screen_time_3h',
        name: 'Screen Time < 3h',
        type: 'number',
        target: 180,
        comparison: 'lte',
        unit: 'min',
        required: true,
        icon: 'screen',
      },
      {
        id: 'screen_time_4h',
        name: 'Screen Time < 4h',
        type: 'number',
        target: 240,
        comparison: 'lte',
        unit: 'min',
        required: true,
        icon: 'screen',
      },
      {
        id: 'screen_time_2h',
        name: 'Screen Time < 2h',
        type: 'number',
        target: 120,
        comparison: 'lte',
        unit: 'min',
        required: true,
        icon: 'screen',
      },
      {
        id: 'pickups_100',
        name: 'Pickups < 100',
        type: 'number',
        target: 100,
        comparison: 'lte',
        unit: '',
        required: true,
        icon: 'screen',
      },
      {
        id: 'pickups_75',
        name: 'Pickups < 75',
        type: 'number',
        target: 75,
        comparison: 'lte',
        unit: '',
        required: true,
        icon: 'screen',
      },
      {
        id: 'pickups_50',
        name: 'Pickups < 50',
        type: 'number',
        target: 50,
        comparison: 'lte',
        unit: '',
        required: true,
        icon: 'screen',
      },
      {
        id: 'no_social_media',
        name: 'No Social Media',
        type: 'boolean',
        required: true,
        icon: 'screen',
      },
      {
        id: 'phone_free_morning',
        name: 'Phone-Free Morning',
        type: 'boolean',
        required: true,
        icon: 'screen',
      },
      {
        id: 'no_phone_bed',
        name: 'No Phone in Bed',
        type: 'boolean',
        required: true,
        icon: 'screen',
      },
      {
        id: 'social_media_time',
        name: 'Social Media < 30min',
        type: 'number',
        target: 30,
        comparison: 'lte',
        unit: 'min',
        required: true,
        icon: 'screen',
      },
    ],
  },
  {
    id: 'mental',
    name: 'Mental Wellness',
    icon: '🧘',
    metrics: [
      {
        id: 'meditation_10',
        name: '10min Meditation',
        type: 'boolean',
        required: true,
        icon: 'meditation',
      },
      {
        id: 'meditation_20',
        name: '20min Meditation',
        type: 'boolean',
        required: true,
        icon: 'meditation',
      },
      {
        id: 'journaling',
        name: 'Daily Journaling',
        type: 'boolean',
        required: true,
        icon: 'reading',
      },
      {
        id: 'gratitude',
        name: 'Gratitude Practice',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
      {
        id: 'breathing',
        name: 'Breathing Exercises',
        type: 'boolean',
        required: false,
        icon: 'meditation',
      },
      {
        id: 'no_complaining',
        name: 'No Complaining',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
      {
        id: 'positive_affirmation',
        name: 'Positive Affirmation',
        type: 'boolean',
        required: false,
        icon: 'check',
      },
      {
        id: 'therapy',
        name: 'Therapy Session',
        type: 'boolean',
        required: false,
        icon: 'meditation',
      },
    ],
  },
  {
    id: 'sleep',
    name: 'Sleep & Recovery',
    icon: '😴',
    metrics: [
      {
        id: 'sleep_7h',
        name: 'Sleep 7+ Hours',
        type: 'number',
        target: 7,
        comparison: 'gte',
        unit: 'hours',
        required: true,
        icon: 'sleep',
      },
      {
        id: 'sleep_8h',
        name: 'Sleep 8+ Hours',
        type: 'number',
        target: 8,
        comparison: 'gte',
        unit: 'hours',
        required: true,
        icon: 'sleep',
      },
      {
        id: 'bed_by_11',
        name: 'In Bed by 11PM',
        type: 'boolean',
        required: true,
        icon: 'sleep',
      },
      {
        id: 'bed_by_10',
        name: 'In Bed by 10PM',
        type: 'boolean',
        required: true,
        icon: 'sleep',
      },
      {
        id: 'wake_early',
        name: 'Wake Before 7AM',
        type: 'boolean',
        required: true,
        icon: 'clock',
      },
      {
        id: 'no_caffeine_after_2',
        name: 'No Caffeine After 2PM',
        type: 'boolean',
        required: true,
        icon: 'clock',
      },
      {
        id: 'no_screens_before_bed',
        name: 'No Screens 1h Before Bed',
        type: 'boolean',
        required: true,
        icon: 'sleep',
      },
    ],
  },
  {
    id: 'productivity',
    name: 'Productivity & Learning',
    icon: '📚',
    metrics: [
      {
        id: 'reading_10',
        name: '10min Reading',
        type: 'boolean',
        required: true,
        icon: 'reading',
      },
      {
        id: 'reading_30',
        name: '30min Reading',
        type: 'boolean',
        required: true,
        icon: 'reading',
      },
      {
        id: 'reading_pages',
        name: 'Read 20 Pages',
        type: 'number',
        target: 20,
        comparison: 'gte',
        unit: 'pages',
        required: true,
        icon: 'reading',
      },
      {
        id: 'deep_work',
        name: 'Deep Work Session',
        type: 'boolean',
        required: true,
        icon: 'target',
      },
      {
        id: 'deep_work_hours',
        name: 'Deep Work Hours',
        type: 'number',
        target: 4,
        comparison: 'gte',
        unit: 'hours',
        required: true,
        icon: 'target',
      },
      {
        id: 'learn_something',
        name: 'Learn Something New',
        type: 'boolean',
        required: false,
        icon: 'reading',
      },
      {
        id: 'daily_goal',
        name: 'Complete Daily Goal',
        type: 'boolean',
        required: true,
        icon: 'target',
      },
      {
        id: 'inbox_zero',
        name: 'Inbox Zero',
        type: 'boolean',
        required: false,
        icon: 'check',
      },
      {
        id: 'no_procrastination',
        name: 'No Procrastination',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
    ],
  },
  {
    id: 'personal',
    name: 'Personal & Habits',
    icon: '✨',
    metrics: [
      {
        id: 'daily_photo',
        name: 'Daily Photo',
        type: 'photo',
        required: true,
        icon: 'photo',
      },
      {
        id: 'cold_shower',
        name: 'Cold Shower',
        type: 'boolean',
        required: true,
        icon: 'water',
      },
      {
        id: 'make_bed',
        name: 'Make Bed',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
      {
        id: 'no_smoking',
        name: 'No Smoking',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
      {
        id: 'floss',
        name: 'Floss Teeth',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
      {
        id: 'skincare',
        name: 'Skincare Routine',
        type: 'boolean',
        required: false,
        icon: 'check',
      },
      {
        id: 'vitamins',
        name: 'Take Vitamins',
        type: 'boolean',
        required: true,
        icon: 'check',
      },
      {
        id: 'connect_friend',
        name: 'Connect with a Friend',
        type: 'boolean',
        required: false,
        icon: 'check',
      },
      {
        id: 'outdoor_time',
        name: '30min Outdoors',
        type: 'boolean',
        required: false,
        icon: 'steps',
      },
      {
        id: 'daily_reflection',
        name: 'Daily Reflection',
        type: 'boolean',
        required: false,
        icon: 'check',
      },
    ],
  },
  {
    id: 'tracking',
    name: 'Habit Tracking (Counter)',
    icon: '📊',
    metrics: [
      {
        id: 'weed_usage',
        name: 'Weed Usage',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'target',
      },
      {
        id: 'masturbation',
        name: 'Masturbation',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'target',
      },
      {
        id: 'caffeine_drinks',
        name: 'Caffeine Drinks',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'energy',
      },
      {
        id: 'cigarettes',
        name: 'Cigarettes',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'target',
      },
      {
        id: 'alcoholic_drinks',
        name: 'Alcoholic Drinks',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'alcohol',
      },
      {
        id: 'snacks',
        name: 'Snacks/Treats',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'diet',
      },
      {
        id: 'glasses_water',
        name: 'Glasses of Water',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'water',
      },
      {
        id: 'workouts_count',
        name: 'Workouts This Week',
        type: 'count',
        tracking: true,
        required: false,
        icon: 'workout',
      },
    ],
  },
];

export const CHALLENGE_TEMPLATES: Omit<ChallengeTemplate, 'id' | 'created_at' | 'created_by'>[] = [
  {
    name: '75 Hard',
    description: 'The ultimate mental toughness program. 75 days of strict discipline.',
    duration_days: 75,
    difficulty: 'extreme',
    category: 'fitness',
    icon: '💪',
    color: '#f97316',
    is_official: true,
    metrics: METRICS_75_HARD,
  },
  {
    name: '75 Soft',
    description: 'A gentler version of 75 Hard with more flexibility.',
    duration_days: 75,
    difficulty: 'hard',
    category: 'fitness',
    icon: '🌟',
    color: '#eab308',
    is_official: true,
    metrics: METRICS_75_SOFT,
  },
  {
    name: '30 Day Challenge',
    description: 'Build a new habit in 30 days.',
    duration_days: 30,
    difficulty: 'medium',
    category: 'habits',
    icon: '🎯',
    color: '#10b981',
    is_official: true,
    metrics: METRICS_30_DAY,
  },
];

export const BADGES: Badge[] = [
  {
    id: 'first_flame',
    name: 'First Flame',
    icon: '🔥',
    description: 'Complete your first day',
    criteria: 'streak >= 1',
  },
  {
    id: 'week_warrior',
    name: 'Week Warrior',
    icon: '⚔️',
    description: 'Maintain a 7-day streak',
    criteria: 'streak >= 7',
  },
  {
    id: 'fortnight_fighter',
    name: 'Fortnight Fighter',
    icon: '🛡️',
    description: 'Maintain a 14-day streak',
    criteria: 'streak >= 14',
  },
  {
    id: 'month_master',
    name: 'Month Master',
    icon: '👑',
    description: 'Maintain a 30-day streak',
    criteria: 'streak >= 30',
  },
  {
    id: 'iron_will',
    name: 'Iron Will',
    icon: '🏆',
    description: 'Complete the full 75 Hard challenge',
    criteria: 'streak >= 75',
  },
  {
    id: 'perfect_week',
    name: 'Perfect Week',
    icon: '💯',
    description: '7 consecutive days with 100% metrics',
    criteria: 'perfect_week',
  },
  {
    id: 'early_bird',
    name: 'Early Bird',
    icon: '🐦',
    description: 'Check in before 9 AM',
    criteria: 'early_checkin',
  },
  {
    id: 'photographer',
    name: 'Photographer',
    icon: '📸',
    description: 'Upload 30 daily photos',
    criteria: 'photos >= 30',
  },
  {
    id: 'social_butterfly',
    name: 'Social Butterfly',
    icon: '🦋',
    description: 'Invite 5 friends to a challenge',
    criteria: 'invites >= 5',
  },
  {
    id: 'consistency_king',
    name: 'Consistency King',
    icon: '📈',
    description: 'Maintain 90%+ completion rate for 30 days',
    criteria: 'completion_rate >= 90 for 30 days',
  },
];

export const BOT_CONFIGS = {
  consistent: {
    name: 'Consistent Carl',
    avatar: '🤖',
    successRate: 0.95,
    variance: 0.03,
    personality: 'Almost perfect, rarely misses',
  },
  human: {
    name: 'Human Hannah',
    avatar: '👩',
    successRate: 0.85,
    variance: 0.1,
    weekendDip: 0.15, // Lower completion on weekends
    personality: 'Realistic patterns with weekend dips',
  },
  struggling: {
    name: 'Struggling Steve',
    avatar: '😅',
    successRate: 0.65,
    variance: 0.2,
    personality: 'Trying hard but inconsistent',
  },
} as const;

export const TIMEZONES = [
  { value: 'America/New_York', label: 'Eastern Time (ET)' },
  { value: 'America/Chicago', label: 'Central Time (CT)' },
  { value: 'America/Denver', label: 'Mountain Time (MT)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (PT)' },
  { value: 'America/Anchorage', label: 'Alaska Time (AKT)' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time (HT)' },
  { value: 'Europe/London', label: 'London (GMT/BST)' },
  { value: 'Europe/Paris', label: 'Paris (CET/CEST)' },
  { value: 'Europe/Berlin', label: 'Berlin (CET/CEST)' },
  { value: 'Asia/Tokyo', label: 'Tokyo (JST)' },
  { value: 'Asia/Shanghai', label: 'Shanghai (CST)' },
  { value: 'Asia/Dubai', label: 'Dubai (GST)' },
  { value: 'Australia/Sydney', label: 'Sydney (AEST/AEDT)' },
];
